[project]
name = "binary-classification"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "autogluon-vision>=0.5.3",
    "torch<2.3.0",
    "numpy>1.22.4",
    "tqdm>=4.67.1",
]
